import re
import os
import subprocess

tableOfPng="<table>\n <tr>"
tableOfPngCount=0;

def clean_string(s,color):
    """
    Return the result of replacing
    "%3E" and "%3C" by ">" and "<"
    and fixes the color to 'color'
    in the supplied string s.
    """
    s1=re.sub("%3E", ">", re.sub("%3C", "<", s))
    s2=re.sub(r"\#\{vf\-url\-friendly\-color\(\$color\)\}",color,s1)
    # set the right size for the twitter logo
    s3=re.sub(r"width\=\'1200\' height\=\'1227\'","width='16' height='16'",s2)
    return s3


def parse_file(file_path):
    """
    Reads a file line by line and prints each line.

    Args:
        file_path (str): Path to the file to be parsed.
    """
    global tableOfPng
    global tableOfPngCount
    try:
        with open(file_path, 'r') as scss_file:
            currentName=""
            for num, line in enumerate(scss_file, start=1):
                m = re.match(r"^@function vf\-icon\-(.*)\-url\(",line)
                if m:
                    currentName=m.group(1)
                    print(f"Line {num}:", m.group(1))
                else:
                    m = re.match(r".*@return url\(\"data\:image\/svg\+xml\,(.*)\"\)\;.*",line)
                    if m:
                        # create black svg file
                        svgFile=currentName+'.svg'
                        try:
                            with open(svgFile, 'w') as svg_file:
                                svg_file.write(clean_string(m.group(1),"#000000"))
                        except PermissionError:
                            print(f"Error: Permission denied to write to file '{svgFile}'.")
                        except Exception as e:
                            print(f"An unexpected error occurred: {e}")
                        # create png out of svg
                        subprocess.run(["inkscape",
                                        "--export-type=png",
                                        "--export-height=256",
                                        "--export-width=256",
                                        svgFile], capture_output=True)
                        # create white svg file
                        svgFile=currentName+'_white.svg'
                        try:
                            with open(svgFile, 'w') as svg_file:
                                svg_file.write(clean_string(m.group(1),"#ffffff"))
                        except PermissionError:
                            print(f"Error: Permission denied to write to file '{svgFile}'.")
                        except Exception as e:
                            print(f"An unexpected error occurred: {e}")
                        # create white png out of svg
                        subprocess.run(["inkscape",
                                        "--export-type=png",
                                        "--export-height=256",
                                        "--export-width=256",
                                        svgFile], capture_output=True)
                        # write contents of README.md
                        tableOfPng=tableOfPng+"""
  <td>
   <table style="border:none;">
    <tr><td>"""+currentName+"""</td></tr>
    <tr>
     <td bgcolor="#101010">
      <img src='https://raw.githubusercontent.com/fderepas/icons/refs/heads/main/icons/"""+currentName+"""_white.svg' width="50" height="50" />
     </td>
    </tr>
    <tr>
     <td>
      svg: <a href='https://raw.githubusercontent.com/fderepas/icons/refs/heads/main/icons/"""+currentName+""".svg'>black</a>,<a href='https://raw.githubusercontent.com/fderepas/icons/refs/heads/main/icons/"""+currentName+"""_white.svg'>white</a>.<br/>
      png: <a href='https://raw.githubusercontent.com/fderepas/icons/refs/heads/main/icons/"""+currentName+""".png'>black</a>,<a href='https://raw.githubusercontent.com/fderepas/icons/refs/heads/main/icons/"""+currentName+"""_white.png'>white</a>.
     </td>
    </tr>
   </table>
  </td>"""
                        tableOfPngCount=tableOfPngCount+1
                        if tableOfPngCount%4 == 0:
                            tableOfPng+="\n </tr>\n <tr>"
    except FileNotFoundError:
        print(f"File not found: {file_path}")

if __name__ == "__main__":
    parse_file('vanilla-framework/scss/_base_icon-definitions.scss')
    try:
        with open("README.md", 'w') as readmeFile:
            readmeFile.write("<!--- Do not edit this file. ")
            readmeFile.write("It is automatially generated by parse.py --->\n")
            readmeFile.write("This git archive stores svg and png files ")
            readmeFile.write("extracted from ```https://github.com/canonical/")
            readmeFile.write("vanilla-framework.git```.\n\n")
            readmeFile.write("Extraction is performed by the ```parse.py``` script.\n")
            readmeFile.write(tableOfPng+"\n </tr>\n</table>\n")
            readmeFile.write("")
    except PermissionError:
        print(f"Error: Permission denied to write to file 'README.md'.")
